server:
  port: 8083
  connection-timeout: 5000ms
  tomcat:
    uri-encoding: UTF-8
spring:
  resources:
    static-locations: classpath:/static/
  profiles:
    active: dev
  thymeleaf:
    mode: HTML
    encoding: utf-8
    cache: false
    prefix: classpath:/templates/
    suffix: .html


  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true
  devtools:
    restart:
      enabled: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.6.22:3306/auth?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: swst
    password: swst
    hikari:
      auto-commit: false
      connection-timeout: 30000
      idle-timeout: 25000
      login-timeout: 5
      max-lifetime: 30000
      read-only: false
      validation-timeout: 3000
      maximum-pool-size: 15
      minimum-idle: 10
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        useLocalSessionState: true
        rewriteBatchedStatements: true
        cacheResultSetMetadata: true
        cacheServerConfiguration: true
        elideSetAutoCommits: true
        maintainTimeStats: false
  mvc:
    static-path-pattern: /static/**

mybatis-plus:
  mapper-locations: classpath:mapper/*Mapper.xml

  global-config:
    banner: false
    db-config:
      db-type: mysql
      field-strategy: not_empty
      id-type: AUTO #主键类型 AUTO:"数据库ID自增", NONE:"用户输入ID"
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
    super-mapper-class: com.baomidou.mybatisplus.core.mapper.BaseMapper

servlet:
  multipart:
    max-file-size: -1
    max-request-size: -1

stream-server:
  ip: "192.168.6.201"
  port: 5062
  code: "60021111000002"
  rec-port-start: 25061
  rec-port-end: 25069
  out_port-start: 30061
  out-port-end: 30069

stream-rec:
  host: "192.168.6.201"
  port: 5060
  code: "60020260000002021"
  tcp-port: 9998
  tcp-history-port: 8998

video:
  url:
    #目录地址
    #    path: "/home/lary_zhong/Documents/nginx-1.17.6/record/"
    path: "/root/video/"
    #
    nginx: "http://192.168.6.153:8099/record/"
  play:
    rollbackTime: "30"
